### ISSUE TITLE
使用portainer部署升级出现问题。 || There is a problem using portainer to deploy and upgrade.

### ISSUE THREAD

**Issue by phantasy36** [blinkospace/blinko#372]
**Describe the bug**
我每次在portainer的stacks中使用docker compose脚本升级都出现数据库无法连接的错误。如果将原有永久化文件夹的数据全部删除后重新部署才行。

**To Reproduce**
升级步骤
1. 进入portainer的stacks菜单中。
2. 进入stacks中的脚本编辑页面。
3. 点击页面底部的update stacks。
4.激活re-pull image and redeploy按钮，重新拉取最新镜像。
5. 点击update，开始重新拉取镜像，并使用运行docker compose脚本运行最新版本blinko。
6. 提示部署成功后出现问题。

**Expected behavior**
部署成功后提示前端无法连接postgresql数据库。

**Screenshots**
<img width="834" alt="{58800065-946D-450E-BE67-677DE9044E24}" src="https://github.com/user-attachments/assets/14d256fc-e847-4ed3-8c22-e83c12b1d8fa" />
数据库运行正常。
<img width="350" alt="{E0841D3E-2B98-440E-BB90-7F00ABF9DCCC}" src="https://github.com/user-attachments/assets/399a2f85-108b-4d1e-ab02-3622010250e5" />

**Desktop (please complete the following information):**
 - OS: 群晖DMS7.2
 - Browser: edge
 - Version: 131.0.2903.112 

**Docker compose**
`networks:
    blinko-network:
      driver: bridge
services:
    blinko-website:
      image: blinkospace/blinko:latest
      container_name: blinko-website
      environment:
        NODE_ENV: production
        # NEXTAUTH_URL: http://localhost:1111
        # NEXT_PUBLIC_BASE_URL: http://localhost:1111
        NEXTAUTH_SECRET: my_ultra_secure_nextauth_secret
        DATABASE_URL: postgresql://postgres:Huhong@postgres:5432/postgres
      depends_on:
        postgres:
          condition: service_healthy
      # Make sure you have enough permissions.
      volumes:
        - /volume5/docker/blinko:/app/.blinko 
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      ports:
        - 1111:1111
      healthcheck:
        test: ["CMD", "curl", "-f", "http://blinko-website:1111/"]
        interval: 30s 
        timeout: 10s   
        retries: 5     
        start_period: 30s 
      networks:
        - blinko-network
    postgres:
      image: postgres:14
      container_name: blinko-postgres
      restart: always
      ports:
        - 5435:5432
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Huhong
        TZ: Asia/Shanghai
      # Persisting container data
      # Make sure you have enough permissions.
      volumes:
        - /volume5/docker/postgresql:/var/lib/postgresql/data
      healthcheck:
        test:
          ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
        interval: 5s
        timeout: 10s
        retries: 5
      networks:
        - blinko-network
`

---
**Describe the bug**
Every time I use the docker compose script to upgrade in portainer's stacks, I get an error that the database cannot be connected. It will only work if you delete all the data in the original permanent folder and then redeploy it.

**To Reproduce**
Upgrade steps
1. Enter portainer’s stacks menu.
2. Enter the script editing page in stacks.
3. Click update stacks at the bottom of the page.
4. Activate the re-pull image and redeploy button to re-pull the latest image.
5. Click update to start pulling the image again, and use the docker compose script to run the latest version of blinko.
6. It prompts that a problem occurred after the deployment was successful.

**Expected behavior**
After successful deployment, it prompts that the front end cannot connect to the postgresql database.

**Screenshots**
<img width="834" alt="{58800065-946D-450E-BE67-677DE9044E24}" src="https://github.com/user-attachments/assets/14d256fc-e847-4ed3-8c22-e83c12b1d8fa" / >
The database is running normally.
<img width="350" alt="{E0841D3E-2B98-440E-BB90-7F00ABF9DCCC}" src="https://github.com/user-attachments/assets/399a2f85-108b-4d1e-ab02-3622010250e5" / >

**Desktop (please complete the following information):**
 - OS: Synology DMS7.2
 - Browser: edge
 - Version: 131.0.2903.112

**Docker compose**
`networks:
    blinko-network:
      driver:bridge
services:
    blinko-website:
      image: blinkospace/blinko:latest
      container_name: blinko-website
      environment:
        NODE_ENV: production
        # NEXTAUTH_URL: http://localhost:1111
        # NEXT_PUBLIC_BASE_URL: http://localhost:1111
        NEXTAUTH_SECRET: my_ultra_secure_nextauth_secret
        DATABASE_URL: postgresql://postgres:Huhong@postgres:5432/postgres
      depends_on:
        postgres:
          condition: service_healthy
      # Make sure you have enough permissions.
      volumes:
        - /volume5/docker/blinko:/app/.blinko
      restart: always
      logging:
        options:
          max-size: "10m"
          max-file: "3"
      ports:
        - 1111:1111
      healthcheck:
        test: ["CMD", "curl", "-f", "http://blinko-website:1111/"]
        interval: 30s
        timeout: 10s
        retries: 5
        start_period: 30s
      networks:
        -blinko-network
    postgres:
      image: postgres:14
      container_name: blinko-postgres
      restart: always
      ports:
        - 5435:5432
      environment:
        POSTGRES_DB: postgres
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: Huhong
        TZ: Asia/Shanghai
      # Persisting container data
      # Make sure you have enough permissions.
      volumes:
        - /volume5/docker/postgresql:/var/lib/postgresql/data
      healthcheck:
        test:
          ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
        interval: 5s
        timeout: 10s
        retries: 5
      networks:
        -blinko-network
`

**Comment by phantasy36** [comment]
还是一样提示连接不上数据库。

**Comment by dcgsteve** [comment]
I am wondering if my issue is the same underlying issue you are having? I have deployed out in Docker Swarm but blinko web app is only listening on one of the two networks attached to the container, i.e. the one associated with the internal container hostname. The other (the main ingress network) is correctly attached as I exposed port 1111 in Swarm, but as the app is only listening to the other IP then I can't get to the UI :(

My current stack is as below - not sure if it helps resolve you issue but def sounds like a container <-> network issue?

```
services:

  blinko-website:
    image: blinkospace/blinko:latest
    environment:
      NODE_ENV: production
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: postgresql://postgres:${DBSECRET}@blinko-postgres:5432/postgres
    hostname: blinko
    # Make sure you have enough permissions.
    volumes:
      - data:/app/.blinko
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - 1111:1111
    healthcheck:
      test: ["CMD", "curl", "-f", "http://blinko:1111/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  blinko-postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DBSECRET}
      TZ: Europe/London
    ports:
      - 5432:5432
    # Persisting container data
    # Make sure you have enough permissions.
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 5s
```
